version: '3.2'
services:
  openvpn-jumphost:
    image: h3mi/openvpn-jumphost:latest
    container_name: openvpn-jumphost
    ports:
      - "8022:22"
    cap_add: 
      - NET_ADMIN
    restart: on-failure
    environment: 
      SSH_PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAAD.........................................AA mail@example.com"
      DEBUG: "true"
    secrets:
      - openvpn_profile

secrets:
  openvpn_profile:
    file: ~/.vpn/openvpn-profile-example.ovpn
